version: '3'

services:
  gimoveisapi:
    build: .
    command: ["npm","start"]
    container_name: gimoveisapi
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - develop-network

  gimoveisfront:
    build: ../gimoveisfront/
    command: npm run serve
    container_name: gimoveisfront
    ports:
      - "8080:8080"
    volumes:
      - ../gimoveisfront/:/usr/src/app
      - /usr/src/app/node_modules/
    networks:
      - develop-network

networks:
  develop-network:
    driver: bridge


